# Autogenerated wrapper script for Powsybl_jll for x86_64-apple-darwin-julia_version+1.9.0
export libPowsyblJlWrap, libmath, libpowsybl_cpp, libpypowsybl_java

using libcxxwrap_julia_jll
using libjulia_jll
JLLWrappers.@generate_wrapper_header("Powsybl")
JLLWrappers.@declare_library_product(libPowsyblJlWrap, "@rpath/libPowsyblJlWrap.dylib")
JLLWrappers.@declare_library_product(libmath, "@rpath/libmath.dylib")
JLLWrappers.@declare_library_product(libpowsybl_cpp, "@rpath/libpowsybl-cpp.dylib")
JLLWrappers.@declare_library_product(libpypowsybl_java, "@rpath/libpypowsybl-java.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, libjulia_jll)
    JLLWrappers.@init_library_product(
        libPowsyblJlWrap,
        "lib/libPowsyblJlWrap.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmath,
        "lib/libmath.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpowsybl_cpp,
        "lib/libpowsybl-cpp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpypowsybl_java,
        "lib/libpypowsybl-java.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
